### ISSUE TITLE
Is there a way to get the amount of money in the bank account?

### ISSUE THREAD

**Issue by sdimantsd** [daniel-hauser/moneyman#101]
I get only the transactions

**Comment by sdimantsd** [comment]
I saw in israeli-bank-scrapers
`    balance?: number, // Account balance. Not implemented for all accounts.
`
But when I try to print it, it's print "undefined". Do you know why is that?

**Comment by daniel-hauser** [comment]
> But when I try to print it, it's print "undefined". Do you know why is that?

Closing for now, after https://github.com/eshaham/israeli-bank-scrapers/issues/743 resolves you can open a PR for adding support for the balance
