### ISSUE TITLE
Cal update to scraper project caused issues

### ISSUE THREAD

**Issue by sohodf** [daniel-hauser/moneyman#129]
Hi again,
2 issues encountered after the update:
1. The following message pops up during scraping:
```
Caught exception: Error: 400: Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
Exception origin: unhandledRejection
```
2. All inactive credit cards are scraped from Cal, not just the ones defined in .env

**Comment by daniel-hauser** [comment]
> The following message pops up during scraping:
Looks like a change in the telegram API, will see how to solve

> All inactive credit cards are scraped from Cal, not just the ones defined in .env
The Cal site has a singe login for all cards, AFAIR was the same in the old site as well

**Comment by sohodf** [comment]
thank you for part 1.

regarding the second part - up until this update, it scraped only the defined credit cards.
after updating, it brings all the cards that ever existed on the account.
it's not a major issue, since those cards do not have transactions, but it's an issue you should be aware of.
you can see an example of 2 scrapes, before and after the change with the same .env file here :
![image](https://user-images.githubusercontent.com/5129050/233506127-759c2871-5ec5-44e4-b914-aee1e1732b5f.png)

**Comment by daniel-hauser** [comment]
Opened https://github.com/daniel-hauser/moneyman/pull/133 to fix issue 1

**Comment by daniel-hauser** [comment]
> it's not a major issue, since those cards do not have transactions, but it's an issue you should be aware of.

You can open an issue on https://github.com/eshaham/israeli-bank-scrapers, maybe its possible to flag an account as canceled, then in moneyman I can ignore accounts that are canceled and have no transactions.

**Comment by daniel-hauser** [comment]
Closing, please reference this issue if you open the issue in israeli-bank-scrapers
