### ISSUE TITLE
Telegram issue

### ISSUE THREAD

**Issue by roisec** [daniel-hauser/moneyman#131]
https://github.com/roisec/moneyman/actions/runs/4759162337/jobs/8458115845

❌ 
Caught exception: Error: 400: Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
Exception origin: unhandledRejection

Parsing config
Telegram logger initialized, status and errors will be sent
Scraping started
uncaughtException, sending error
uncaughtException, sending error
uncaughtException, sending error

**Comment by daniel-hauser** [comment]
@roisec Fixed in #131
