### ISSUE TITLE
JSON file doesn't indicate the companyType

### ISSUE THREAD

**Issue by gczobel** [daniel-hauser/moneyman#165]
When several accounts are indicated, there is no possibility to understand in the transaction from where the transactions are coming.
For example, a single Isracard account can return several CCs, and, in this case, the 'account' field will be the last 4 numbers of the credit card.
If several accounts are requested, there is no possible way (except of looking in the hash field) to know the `companyID`.

  {
        "account": "123456789",
        "chargedAmount": 2683,
        "date": "2023-07-23T21:00:00.000Z",
        "description": "blah"
        "hash": data+chargedAmount+description+memo+companyId+accountNumber
        "identifier": 12799000803480,
        "memo": "",
        "originalAmount": 2683,
        "originalCurrency": "ILS",
        "processedDate": "2023-07-23T21:00:00.000Z",
        "status": "completed",
        "type": "normal"
    },

**Comment by daniel-hauser** [comment]
Good idea! thanks for creating a PR
