### ISSUE TITLE
Issue with export to JSON file

### ISSUE THREAD

**Issue by sohodf** [daniel-hauser/moneyman#182]
Hi Daniel, and thank you for his project.

I've been using it for a while, and recently updated to a newer version.
I'm having trouble with exporting to a local JSON file.
i have.the LOCAL_JSON_STORAGE set to true in the .env file, but no file is created.

When running with docker, it says that the file was successfully created, but no actual file exists.
I tried running with NPM directly, but got another error with creating the file - ENOENT: no such file or directory.

I tried this on another machine i have with the same result.
BTW, it worked fine before pulling the latest version from the repo.

What do you think?

**Comment by sohodf** [comment]
adding that after further testing, resetting back to a march commit (2f41d), made the issue disappear, so this is probably a regression.

**Comment by daniel-hauser** [comment]
Seems like the bug is only when running on windows due to the use of `:` in the file name.
Fixed in #188

**Comment by sohodf** [comment]
Thank you for the fix.
However, I don't think it's windows-only related, because I saw this issue both on windows and on mac-os.
After pulling the latest code and fixing the docker file to include the local volume, it worked fine, so the fix is valid on 2 OSs :)
