### ISSUE TITLE
Max issue 

### ISSUE THREAD

**Issue by orenazar** [daniel-hauser/moneyman#203]
Hi 
I have an issue with MAX checked the paswword and rest and still the same issue
anyone have any idea why ?

Orenbot, [7 Dec 2023 at 12:40:25]:
Config:
  Worksheet name: _moneyman
  Start Date: 2023-11-27T10:40:24.620Z (10 days back)
  TZ: Asia/Jerusalem

[visaCal] END_SCRAPING, took 17.3s
[visaCal] END_SCRAPING, took 15.8s
[max] END_SCRAPING, took 30.2s

total time: 64.1s

Accounts updated:
 ✔️ [visaCal] 1080: 17
 ✔️ [visaCal] 2380: 19
 ✔️ [visaCal] 1564: 7
 ✔️ [visaCal] 1696: 0
 ✔️ [visaCal] 1098: 0
 ✔️ [visaCal] 8011: 0
 ❌ [max] GENERIC
 Navigation timeout of 30000 ms exceeded
Saved to:
📝 Google Sheets (_moneyman)
    7 added, 36 skipped
    (36 existing,  0 pending)

**Comment by daniel-hauser** [comment]
My max cards are working properly, can you do a local run with `showBrowser: true` and see what's on the screen?

**Comment by daniel-hauser** [comment]
My max cards are working properly, can you do a local run with `showBrowser: true` and see whats on the screen?

**Comment by orenazar** [comment]
HI Daniel
I didn't the chance to do that but it start working with no reason and failed again without doing any change
