### ISSUE TITLE
Leumi and Mizrahi problems

### ISSUE THREAD

**Issue by maximbaran** [daniel-hauser/moneyman#212]
Hi,

I am experiencing a general error when scraping data from Leumi and Mizrahi banks. I have tried both locally and via a GitHub workflow.

I am receiving the following error message:

```
0 transactions scraped.

Accounts updated:
 ❌ [leumi] GENERIC
  waiting for selector #enter_your_account a failed: timeout 30000ms exceeded
 ❌ [mizrahi] GENERIC
  Cannot read properties of undefined (reading 'getProperty')

Saved to:
 😶 None
-------
Pending txns:
 😶 None
```

Do you have any idea what could be causing this issue?

**Comment by daniel-hauser** [comment]
I don't have account from leumi and mizrahi so can't test.

Can you do a local run with `showBrowser: true` and see what's on the screen?
