### ISSUE TITLE
YNAB support

### ISSUE THREAD

**Issue by gczobel** [daniel-hauser/moneyman#214]
Just that... what about YNAB support?
It's not a lot of work... a couple of env vars for the YNAB token, budget and accounts and convert from Moneyman to YNAB format the transactions.

@daniel-hauser  WDYT about a pull request to support it?

**Comment by daniel-hauser** [comment]
I don't use YNAB so can't do it, but a PR to add a storage for YNAB is welcomed!

**Comment by gczobel** [comment]
First draft in #218

**Comment by amihaiOff** [comment]
@gczobel @daniel-hauser i have python code that can upload to YNAB if thay helps
