### ISSUE TITLE
Question: Bug or doc typo?

### ISSUE THREAD

**Issue by gczobel** [daniel-hauser/moneyman#254]
The documentation defines ACCOUNTS_TO_SCRAPE as "A comma separated list of providers to take from ACCOUNTS_JSON. if empty, all accounts will be used" with default value `[]`
Now, with the current code, https://github.com/daniel-hauser/moneyman/blob/main/src/config.ts#L33 only setting the env variable in the following way works

`ACCOUNTS_TO_SCRAPE=max,isracard`

setting in another way, for example `=["max", "isracard"]` and even `"max", "isracard"` do not work and **no account** is scraped.

**Comment by daniel-hauser** [comment]
Yes, it's a typo in the docs. Thanks for spotting it, I'll fix it
