### ISSUE TITLE
`npm install` fails in arm64 systems

### ISSUE THREAD

**Issue by glekner** [daniel-hauser/moneyman#265]
`npm install` fails in Apple silicon systems with the following error:
```
npm ERR! The chromium binary is not available for arm64.
```

 suggest adding this to the readme:
if you're using an Apple silicon man, install chromium manually and add the following env variables:

```bash
brew install chromium --no-quarantine

// env
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`
```

**Comment by daniel-hauser** [comment]
Fixed in #299
