### ISSUE TITLE
Trouble reading the GOOGLE_PRIVATE_KEY from env file - error:1E08010C:DECODER routines::unsupported

### ISSUE THREAD

**Issue by NoamGit** [daniel-hauser/moneyman#29]
When using the `docker run` I get
```2022-05-07T15:50:49.602Z moneyman:notifier ❌ Error: error:1E08010C:DECODER routines::unsupported```

I've investigated and it happens because the .env file parsing fails

```
...
GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----****\n-----END PRIVATE KEY-----\n"
...
```

How would you structure the RSA key for GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY?

_What I've tried?_
- Multiline with """ in the .env file
- Passing it as an entrypoint 'export GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=...`

**Comment by daniel-hauser** [comment]
Tested now - you are right, my bad.

docker doesn't support multiline env variables, I use docker compose that dose support it.
For now, use `docker compose up` to run it, ill try to find a fix for docker (or fix the documentation)

**Comment by ofek-a** [comment]
@daniel-hauser How do you make this work with the `scrape.yml` action? since it's using `docker run`

**Comment by ofek-a** [comment]
@daniel-hauser Not sure if this is the best solution, but I ended up encoding the `GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY` key as base64, then decoding it inside the `initDocAndSheet()` function.

Here is the code for those interested, dirty, but works:

```typescript
private async initDocAndSheet() {
    const doc = new GoogleSpreadsheet(GOOGLE_SHEET_ID);

    const {
      GOOGLE_SERVICE_ACCOUNT_EMAIL: client_email,
      GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: private_key_base_64_encoded,
    } = process.env;

    const private_key_decoded = Buffer.from(
      private_key_base_64_encoded || "",
      "base64"
    )
      .toString("utf8")
      .replace(`"`, "");

    if (client_email && private_key_decoded) {
      logger("Using ServiceAccountAuth");
      await doc.useServiceAccountAuth({
        client_email,
        private_key: private_key_decoded,
      });
    }

    await doc.loadInfo();

    if (!(worksheetName in doc.sheetsByTitle)) {
      logger("Creating new sheet");
      const sheet = await doc.addSheet({ title: worksheetName });
      await sheet.setHeaderRow(GoogleSheetsStorage.FileHeaders);
    }

    this.sheet = doc.sheetsByTitle[worksheetName];
  }
```

**Comment by tomer-porat** [comment]
Unfortunately the base64 encoding method was unsuccessful for me. 
However, I have found an alternative solution that does not necessitate any modifications to the code:
https://github.com/vercel/next.js/discussions/38430#discussioncomment-3544992
