### ISSUE TITLE
not scraping accounts json

### ISSUE THREAD

**Issue by ohadperry** [daniel-hauser/moneyman#302]
```
ACCOUNTS_JSON=[{"companyId":"hapoalim","userCode":"AB1234","password":"p@ssword"}]
```

out put has no errors 

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/4ebec231-a8cb-4be5-8c49-63b8d72d249b">

but no accounts are scrapped

**Comment by daniel-hauser** [comment]
You can run with [`DEBUG=moneyman:*`](https://github.com/daniel-hauser/moneyman?tab=readme-ov-file#debug) and see the errors.

**Comment by ohadperry** [comment]
thanks helped a lot. 
still getting this error but that's related to the scrapper
<img width="1297" alt="image" src="https://github.com/user-attachments/assets/2b9f602e-e352-4d47-b9c7-e6d5d1711917">
