### ISSUE TITLE
Getting error only on Docker action flow - [beinleumi] GENERIC   Navigation timeout of 30000 ms exceeded 

### ISSUE THREAD

**Issue by nisan-tagar** [daniel-hauser/moneyman#321]
Started getting this exception as of last week (since 8/8/24 or so ... ) only when executed via the Docker build on the Github action flow. When I run the same code on my local machine the bank is scrapped with no timeout issues.
@daniel-hauser - Could it be related to recent docker image or other env changes made?

**Comment by daniel-hauser** [comment]
I saw a similar issue with amex and isracard in the past month. in their case they were blocking traffic from out of Israel.
If you have access to a US virtual machine you try logging in from there and verify that this is not the problem

**Comment by nisan-tagar** [comment]
Yep @daniel-hauser this issue resolved by itself eventually.
I tried reproducing via US VPN but I was always able to login every time. 
I suspect perhaps the public GitHub action machine might have some perf limitations causing the timeouts.
