### ISSUE TITLE
pull docker image not work on forked repo

### ISSUE THREAD

**Issue by roisec** [daniel-hauser/moneyman#79]
Hi,
When you do a fork to my other repo, the docker image can't be pulled.
this is because the name of the docker should be your repo name and not another. see below:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:latest

Or I'm confused and the docker image should build on my ecr repository?

**Comment by daniel-hauser** [comment]
Yes, when cloning the repo, the build task should run and build your own image.

This is by design
