### ISSUE TITLE
Duplicate transactions in google sheet

### ISSUE THREAD

**Issue by roisec** [daniel-hauser/moneyman#80]
Hi,
When I start the scaper manually, I saw duplicates in transactions.
When I trigger the action again, all the transactions are written several times.
note: The hash field exists and I don't touch him.

**Comment by roisec** [comment]
I solved the issue by setting your headers in my current spreadsheet.

**Comment by daniel-hauser** [comment]
Assuming you use the google sheets storage (the only one that currently supports hashes), the hash column MUST have `hash` as the title.

Closing this issue.
If the duplications happened with `hash` as the header - feel free to reopen
