### ISSUE TITLE
Where docker save the 'json' output?

### ISSUE THREAD

**Issue by sdimantsd** [daniel-hauser/moneyman#98]
Hi, 
Thanks!
I am using the json output. 
I get this message:
Saved to:
📝 LocalJsonStorage (/app/output/2022-11-30T07:23:38.285Z.json)

But there is no dir '/app/output/'
And also, there is no file named '2022-11-30T07:23:38.285Z.json' in all of me computer.
So the question is, where the json saved and how can I change it?

**Comment by daniel-hauser** [comment]
You can use [docker volumes](https://docs.docker.com/storage/volumes/) to persist files on the host.

For example (from the back of my head) `docker run --rm -v /some/path:/app/output --env-file ".env" ghcr.io/daniel-hauser/moneyman:latest`

**Comment by sdimantsd** [comment]
It's doesn't work, I get an error:
Error: EACCES: permission denied, open '/app/output/2022-12-04T08:52:19.793Z.json'
